# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqrEdHL30F6AywqVa2SFzTidcikBr735
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([55,15,10,20])
mylabels=["uyqu vaqti","ovqatlanish vaqti","bosh vaqt","dars vaqti"]
plt.pie(x,labels=mylabels)
plt.show()